name: Cypress Tests for WICK-A11Y Video Tutorial

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      
      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Upload npm error log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-error-log
          path: /home/runner/.npm/_logs/*.log